server:
  port: 9002

  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000

spring:
  servlet:
    multipart:
      max-request-size: 10MB # 上传文件总的最大值
      max-file-size: 10MB # 单个文件的最大值

  mail:
    #        host: smtp.qq.com
    host: smtp.exmail.qq.com
    #        username: 792075058@qq.com
    username: muxiannian@mxnzp.com
    #        password: mzsfuxlsvlzobedb
    password: Cretin**29**
    default-encoding: UTF-8
    ssl:
      trust: smtp.exmail.qq.com
    properties:
      mail:
        smtp:
          auth: true  #是否需要认证
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL证书Socket工厂
            port: 465 #587

debug: false
